### ISSUE TITLE
Create a menu

### ISSUE THREAD

**Issue by samuelrjacobson** [samuelrjacobson/381-Python-Exercise#1]
**User story**

As a user, I want an easy way to exit from the program.

* person: user who wants to be able to exit
* feature: program features a menu allowing user to exit from program
* business value: the user will be able to exit

**Task List**
- [x] Add a menu responding to user prompts
- [x] If user enters q, quit
- [x] If user enters anything else, restart menu

**Acceptance Criteria**
1. Menu allows user to exit
2. Menu restarts if any other value is entered

**Acceptance Test**
If user enters q, quit; otherwise, display menu again
