### ISSUE TITLE
Allow search by movie name

### ISSUE THREAD

**Issue by samuelrjacobson** [samuelrjacobson/381-Python-Exercise#3]
**User story**

As a user, I want to be able to search the movie names.

* person: user who wants to search movies
* feature: user can search movies
* business value: user will now be able to see what movies are in database

**Task List**
- [ ] Add an option to the menu
- [ ] If user enters sn, prompt for a string
- [ ] Search the movie names for that string, and display those that match

**Acceptance Criteria**
1. Menu includes search by name option
2. Program displays accurate results from searching by name

**Acceptance Test**
If user enters sn, program asks for a string, then displays the correct results after the string is entered
