### ISSUE TITLE
Allow search by cast

### ISSUE THREAD

**Issue by samuelrjacobson** [samuelrjacobson/381-Python-Exercise#4]
**User story**

As a user, I want to be able to search the names of cast members.

* person: user who wants to search by cast names
* feature: user can search movies by cast name
* business value: user will now be able to see which movies feature specific actors

**Task List**
- [ ] Add an option to the menu
- [ ] If user enters sc, prompt for a string
- [ ] Search the cast names for that string, and, for every movie that has someone with that name in the cast, display the movie name and cast member/s.

**Acceptance Criteria**
1. Menu includes search by cast option
2. Program displays accurate results from searching by cast

**Acceptance Test**
If user enters sc, program asks for a string, then displays the correct results after the string is entered. Correct results include the name of the movie and list of cast with that name, for each movie with a cast member with that name.
